name: flutter_custom_tabs
description: A Flutter plugin to use Chrome Custom Tabs.
version: 0.0.1
author: Shinya Kumagai
homepage: https://github.com/droibit/flutter_custom_tabs

environment:
  sdk: ">=2.0.0-dev.28 <2.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: "^3.0.0"

flutter:
  plugin:
    androidPackage: com.github.droibit.flutter.plugins.customtabs
    pluginClass: CustomTabsPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter